language: go
go:
- 1.2
- tip

install:
- go get -v ./...
- go get github.com/onsi/ginkgo
- go get github.com/onsi/gomega
- go install github.com/onsi/ginkgo
- go install github.com/onsi/gomega

script: go test
